### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by davidcaron**
All tests pass for both python 2 and 3. I built upon the last pull request and as far as I know, this seems to work like it should...

### CODE REVIEW

**Comment by hobu** [comment]
We need Travis so we can set it up to run the test suite when we get PRs like this. It will go a long way in smoothing these kinds of PRs.

@grantbrown there should be an email in your box to approve this request.

**Comment by grantbrown** [comment]
@hobu done

**Comment by hobu** [comment]
Can you make a silly commit to this PR to trigger the travis build? I think I have it all linked up again. https://travis-ci.org/laspy/laspy/builds

**Comment by hobu** [comment]
:shipit: 😄

**Pull request merged**
