### PR TITLE
Ignore characters that cannot be decoded instead of erroring.

### PR DESCRIPTION
**Pull request by arknoll**

### CODE REVIEW

**Comment by tmontaigu** [comment]
I wonder if storing the raw bytes when we encounter an encoding error would be better.

If we simply ignore on error, that would mean we may lose data ?

**Comment by hobu** [comment]
> I wonder if storing the raw bytes when we encounter an encoding error would be better.

IIRC, newer versions of the spec say this should be UTF-8, so someone doing it is out of compliance.

> If we simply ignore on error, that would mean we may lose data ?

Yes

**Comment by tmontaigu** [comment]
> > I wonder if storing the raw bytes when we encounter an encoding error would be better.
> 
> IIRC, newer versions of the spec say this should be UTF-8, so someone doing it is out of compliance.
> 

Seems fair.

In 1.0 it seems like the 32bytes could be anything.
In 1.1 to 1.3 says that if the system_identifier is not one of the proposed 'string' then it should be "a string up to 32 characters identifying the operation" without precising the encoding.
1.4 adds strings to the datatype as " a variable series of 1 byte characters, ASCII encoded, null terminated"

Generating software has always been declared as being ascii

**Comment by tmontaigu** [comment]
Thanks

**Comment by jo-chemla** [comment]
Some softwares encode las files VLRs using another encoding-system - not utf8 but latin1 in the case of RealityCapture for example. Should laspy default to decode using ~UTF-8~ ASCII as @hobu mentioned the spec now requires, but also provide a way for users to chose another bytes encoding/decoding? Or should it stick to only ASCII decoding? 

As a note, the below laspy code fails for decoding exception for the concerned las files, and the alternative at the moment is to take the std_output and decode it using the desired encoding. 

```py
# Failing for las files with bad encoding: 
with laspy.open(las_fp) as fh:
    for points_chunk in fh.chunk_iterator(1):
        las_min = np.array([fh.header.x_min, fh.header.y_min, fh.header.z_min])

# Alternative to parse the std_output
result = subprocess.run([pdal_exe, 'info', '--metadata', las_fp], stderr = subprocess.PIPE, stdout = subprocess.PIPE) 
json_result = json.loads(result.stdout.decode('latin-1'))  # or utf-8 or nothing which defaults to utf8

```

**Comment by hobu** [comment]
Maybe it would be helpful for laspy to try `latin-1`, `utf-8`, and `ASCII` encodings (in that order) for any of the header entries. That would include software_id and generating_software, any of the extra byte names, etc. 

Be liberal in what you accept, I guess, but this is kind of gross. If someone has a contact to the RealityCapture team, please reach out to them with this ticket. They're writing incorrect data.

**Comment by jo-chemla** [comment]
Yes that could be helpful for laspy to try these different encodings - if letting the user decide of an encoding would not be ideal. Out of curiosity, why do you suggest this order if the spec requires `ASCII` and the probably most adopted solution after this one is `utf-8` ? So all header entries of most las files would succeed at the first try when decoding using `ASCII` without needing to try all options. 

And I just reached out to RealityCapture support on their community forum [here](https://support.capturingreality.com/hc/en-us/community/posts/4407570574994-LAS-VLRs-are-ancoded-in-latin1-instead-of-UTF8-or-ASCII-), waiting for their feedback.

**Comment by hobu** [comment]
I chose that order because it would be the most uncommon to most common ordering, but maybe this isn't the best idea. @tmontaigu may have some different ideas.

**Comment by tmontaigu** [comment]
In the alternative in your code example, you use pdal wich means that pdal is able to read files with non ascii ecoding for string fields.

What I would do is if the utf-8/ascii decoding fails, we store the raw `bytes` read, otherwise we do as usual and store the decoded string.

And  when writting, we would then check the encoding if we have `bytes`, or encode if we have a `str` and throw error if
that step fails. 

With that we would be very liberal in what we read but convervative in what we write. 
And maybe add another option to ignore encoding error when writting.

**Comment by jo-chemla** [comment]
Indeed this seems like a great option! Then the user would have the ability to decode header fields using an encoding of choice if it is known to be something outside of the spec, while ensuring writing is following spec if not raw bytes.

**Pull request merged**
