### PR TITLE
Updated README and setup script.

### PR DESCRIPTION
**Pull request by kbevers**
Changed file name of README.md to README.rst to reflect the content
of the file which is formatted as restructured text. Added a short
intro section, an example and updated the installatian guide.

setup.py now reads the README file and uses it for the long
description for the package. That is also the text that is
shown on PyPI. Furthermore the URL was updated to the new github
page under the laspy organization and the development status was
changed to 'Production/Stable'.

### CODE REVIEW

**Comment by hobu** [comment]
Are we ready to release? We need a ChangeLog added to the README, I suppose.

**Comment by kbevers** [comment]
Soon I guess. I just noticed that I left a few unused imports in setup.py. I'll fix that first at least.

**Comment by kbevers** [comment]
If you are happy with the README, I would say that we are ready to release.

**Comment by hobu** [comment]
> If you are happy with the README

It needs a changelog for items fixed/added since the last release. After that, I think we're good.

**Comment by kbevers** [comment]
Of course. Have we got it all covered under milestone 1.5?

**Comment by hobu** [comment]
I only put stuff under milestone 1.5 that I actually touched. I haven't done a full pass to see what might have changed since the last release. A bit more digging to pull it together is required.

**Comment by kbevers** [comment]
Actually two out of five was introduced in earlier releases. Changes since 1.4.2 is Python3 support, bug fix related to LAS v. 1.4 and the circular references thing (which is actually two different changes). I'll add those.

**Comment by kbevers** [comment]
Version number still needs to be bumped, but apart from that I think we are good to go. Please merge this if you are happy with it, @hobu

**Pull request merged**
