### PR TITLE
Fix/open read only

### LINKED ISSUE #66: Cannot open file in read-only mode without write permission
When we try to open a read-only file (no write permission) with mode="r", it is changed internally to "r+" before trying to open the file on[ laspy.base.DataProvider.open()](https://github.com/laspy/laspy/blob/master/laspy/base.py#L122).

Mode "r+" expects write permission, so the open fails, and laspy stops with the exception raised on [laspy/base.py, line 128](https://github.com/laspy/laspy/blob/master/laspy/base.py#L128)

Problem found on laspy 1.5.0.

### PR DESCRIPTION
**Pull request by Ellon**
Fixes #66 

Also fixes raising exception when mode is not supported.

### CODE REVIEW

**Comment by kbevers** [comment]
Judging by the tests your fix has introduced a new bug. Or at least the tests aren't compatible with your patch. Either way, something needs changing before this can be merged.

**Comment by Ellon** [comment]
I see. I'm taking another look at it.

**Comment by Ellon** [comment]
The problem was that, for some reason, the DataProvider cannot be opened with "w" when remapping.

**Comment by kbevers** [comment]
Thank you for finding and fixing this bug.

**Pull request merged**
