### PR TITLE
Convert np.alltrue to np.all calls to address deprecation warning.

### PR DESCRIPTION
**Pull request by hobu**
Note this would require bumping the minimum Numpy version to 1.25. The calls to `alltrue` will no longer work in Numpy 2.0, however.

### CODE REVIEW

**Comment by hobu** [comment]
It seems that laszip + macos is no longer a working combo.

**Comment by tmontaigu** [comment]
There is an extra `S` in `cliS` here https://github.com/laspy/laspy/blob/dcf0ff076fd801e768a9138d71f28da611ed8c8f/.github/workflows/build.yml#L36C1-L36C68

Strange that only bugs now and did not before

**Comment by tmontaigu** [comment]
Ok, it seems that the problem is that the github images are using a newer version of macOs for which laszip does not have compatible wheels yet

**Comment by hobu** [comment]
> Ok, it seems that the problem is that the github images are using a newer version of macOs for which laszip does not have compatible wheels yet

Yes, this is why I suggested vendoring the LASzip code into laszip-python to make it easier to build and manage those.

https://github.com/tmontaigu/laszip-python/issues/12

**Pull request merged**
