### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by sethrh**
Hi, here are some changes that make this also run in python 3. 

I've been using it in python 3.4.3 with lots of las files for the last month or so, it seems to work pretty well.

### CODE REVIEW

**Comment by grantbrown** [comment]
Thanks for working on this. I'll try to find some time over the weekend to test it out. 

One think I worry about is the skipped tests; all of the tests should work in version 2.7.

**Comment by sirgogo** [comment]
Does anyone know the status of this? I'm looking for python3 support, and willing to help in any way. I forked @sethrh 's fork, but I get stuck trying to import laspy, despite the fact that there is a .__init__.py file in there. Only ran `setup.py build`, did not `install`.

**Comment by grantbrown** [comment]
The fork should work fine, as it appears to be passing most of the tests. What folder are you in when you try to import (the built but not installed) laspy? 

The only holdup in merging this back into main is that I haven't had a chance to go dig into the reasons why there were problems with some of the tests (See [This commit](https://github.com/grantbrown/laspy/pull/45/commits/22e4d69fa0615069806449336aba1c2bb582e524)).

If you can dig into the tests we can move forward with the merge.

**Comment by sirgogo** [comment]
1. I figured out that I needed LAStools, or at least laszip in my path, since I am reading `.laz` files.
2. I had to modify several files in order for import/build/install, because maybe they're not compatible with Python 3.5.1?
3. (After `pip uninstall`): I still get an error on reading (note that I am in repo folder)
```
[arajagopal@arl01 laspy-fork]$ ls                                                                                                  
build  doc    laspy.egg-info  LICENSE.txt  misc        README.rst  simple1_3.las  simple.las 
dist   laspy  laspytest       MANIFEST.in  publish.sh  setup.py    simple1_4.las  simple.laz                                       
[arajagopal@arl01 laspy-fork]$ python3                                                                                             
Python 3.5.1 (default, Jun 13 2016, 16:14:50)                                                                                      
[GCC 6.1.1 20160510 (Red Hat 6.1.1-2)] on linux                                                                                    
Type "help", "copyright", "credits" or "license" for more information.                                                             
>>> import laspy                                                                                                                   
>>> inFile = laspy.file.File("../LiDAR_6989/data/A245880.laz", mode = "r")                                                         
Error Parsing EVLR Body Data:                                                                                                      
'float' object cannot be interpreted as an integer   
```
Maybe I'm doing something wrong?

4. I guess I will try pulling from 2.x repo, and trying changes one by one..?

**Comment by brycefrank** [comment]
Has anyone else had trouble accessing the wkt information from the header using this version? I have tried a couple of different las files and have the same error. I'm convinced that at least one of these files indeed has wkt in it.

```
import laspy

las_file = laspy.file.File(r"C:\my_las.las")

print(las_file.header.wkt)
```

Results in the output:

```
Traceback (most recent call last):
  File "C:/pyfor/_sandbox.py", line 89, in <module>
    print(las_file.header.wkt)
  File "C:\Python35\lib\site-packages\laspy\header.py", line 695, in get_wkt
    raise util.LaspyException("WKT not present in data_format_id " + str(self.data_format_id))
laspy.util.LaspyException: WKT not present in data_format_id 1
```

Could anyone quickly check if they get the same error running this version?

**Comment by kbevers** [comment]
This only works for LAS  v. 1.4 files, since WKT SRS representation was first introduced in that version. Before that GeoTIFF was used for SRS representation. In LAS v. 1.4 both can be used. So you need to be sure that your files is LAS v. 1.4 AND uses WKT for representing the spatial reference.

As far as I can see the exception is raised in both in python2 and python3 versions of laspy.

**Comment by brycefrank** [comment]
That would explain things. Thanks for the help Kristian!

**Comment by hobu** [comment]
Please confirm, but I think this has all been superseded by #62

**Pull request merged**
