### PR TITLE
Handle redundant CSs in GeoKeyDirectoryVlr

### PR DESCRIPTION
**Pull request by fabiopicchi**
Some LAS files with their positioning data stored in a Projected Coordinate System might have the corresponding Geographic Coordinate System redundantly set. The current parse_crs implementation will spit the first CRS it finds in the GeoKeyDirectoryVlr, yielding the wrong one when both are set.

This PR will solve this issue by prioritizing the Projected CS when both are set. The autzen.las file was updated to include this redundancy in its headers.

### CODE REVIEW

**Comment by fabiopicchi** [comment]
@tmontaigu I tweaked the autzen.las file and added the GeographicCS there (the ProjectedCS was already there). Do you want me to add other files that have projected only and geographic only?

**Comment by tmontaigu** [comment]
That can be cool if you can have that
Having tests means less chance of introducing a regression  later😁

**Comment by fabiopicchi** [comment]
Done, @tmontaigu  :)
Sorry for taking so long to do this. I hope this test is enough

**Comment by tmontaigu** [comment]
Thanks for this

**Pull request merged**
