### PR TITLE
Delete circular references in close. Avoid call to build_point_refs

### PR DESCRIPTION
**Pull request by silyko**
Will try to be a little more memory friendly by deleting objects in base.FileManager which holds references to self, before the FileManager is set to None in file.File.close. 
Also try to avoid building the long list of point_refs in FileManager. This seems to be only used in a few methods, which should perhaps be updated or deprecated?

### CODE REVIEW

**Comment by silyko** [comment]
Have also implemented a r- open mode, which won't construct the point map. This means that only the header is available - also for compressed files. This can be useful, e.g. to open compressed files in some automated processing system, read number of points and extent, and only then decide if one wants to call File.reopen(mode=r). Or whether some subtiling with laszip is needed first.

This at least makes sense for me, in some use cases that I have.

**Comment by grantbrown** [comment]
Thanks, I'll add this to the list of things to review. Sorry I've been so slow to merge these changes, I've been pretty swamped dealing with end of semester duties.

**Comment by kbevers** [comment]
I had a look at this. Seems fine to me and I also have use cases where the ```"r-"``` flag makes sense.

@silyko I'll merge this if you fix the conflict in ```laspytest/test_laspy.py/``` and a section to the docs about the ```"r-"``` flag.

**Comment by silyko** [comment]
Great! Will fix the conflict - at some point in the coming weeks :)

**Comment by hobu** [comment]
Can you get this deconflicted and the Travis tests passing this week? We are going to have a 1.5.0 release on Friday 31 Mar.

**Comment by silyko** [comment]
Been pretty busy lately, sorry for the delay. But if it still seems relevant I should be able to fix this probably by tomorrow. Shouldn't take so long.

**Comment by hobu** [comment]
> Shouldn't take so long.

Excellent. Appreciate the PR, sorry it's taken so long to get it incorporated.

**Comment by silyko** [comment]
So - seems to be OK.

**Pull request merged**
