### PR TITLE
Spelling/Typos fixes

### PR DESCRIPTION
**Pull request by glostis**
Hi!

This is a PR that fixes a few spelling mistakes/typos I've encountered (mainly in the documentation), and that updates the link to the repository in the documentation.

Thanks!

### CODE REVIEW

**Comment by glostis** [comment]
@hobu Thanks for the quick merge!

About the failing builds (https://travis-ci.org/github/laspy/laspy/builds/677273194), I managed to solve them by doing `pip install --upgrade numpy lazperf` in the `.travis.yml` (see https://travis-ci.com/github/glostis/laspy/builds/161055705) but I'm not sure how robust of a fix this is, since I don't know anything about `lazperf`'s requirements and how it is built.

**Comment by hobu** [comment]
I was just a review. I was waiting for @kbevers or @grantbrown to actually merge. I haven't been tracking this closely enough to feel confident to merge things.

**Comment by glostis** [comment]
Yes my bad, I read the email a bit too quickly...

**Comment by kbevers** [comment]
>  I haven't been tracking this closely enough to feel confident to merge things.

@houb I don't think any of us tracks this particularly closely these days. But seeing as these are just spelling errors being corrected it should be fine. It would be nice if Travis didn't fail but that seems to be an unrelated issue in lazperf.

**Comment by glostis** [comment]
@kbevers as mentioned here: https://github.com/laspy/laspy/pull/124#issuecomment-616593814 I've found a way to make Travis pass (see patch: https://github.com/laspy/laspy/compare/master...glostis:failing-builds).

I don't really understand exactly what's going on so this may not be the most robust solution, but if you're happy with the `pip --upgrade` patch I can open a separate PR with it.

**Comment by kbevers** [comment]
> I don't really understand exactly what's going on so this may not be the most robust solution, but if you're happy with the pip --upgrade patch I can open a separate PR with it.

It's probably just Travis that has older default packages. It is quite normal to run a `pip --upgrade` as part of the Travis config. If this fixes the problem it's fine. You don't need to open another PR, just add another commit to this one. Thanks.

**Pull request merged**
